# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7d1e4aa9ad7c05188331a92d491585a4c590eb59581d5372563e06b0271eb59f57602c60aaaf2e88e4277b3452b81db99d45265b8b088e9772b2c49b09a6efe

test:
  secret_key_base: 58ccb4005c1afa62cff3a04480abeb1f19fad0aaca5f1176145524c5de7b8d2850af8a81ef79dea47ee2ca3d24ec00d9c91f2d4a937753b4df4602d2e99cb5b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
